services:
  app:
    container_name: grocereach-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '8080:8080'
  redis:
    container_name: grocereach-redis
    image: 'redis:7.4'
    ports:
      - '6379:6379'

volumes:
  postgres_data: